name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t suryathink/globetrotter:latest ./server

      - name: Validate Build
        run: |
          docker run --rm suryathink/globetrotter:latest npm run build

      - name: Push Docker Image to Docker Hub
        run: |
          docker push suryathink/globetrotter:latest

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Decode and Save SSH Key
        env:
          EC2_KEY_BASE64: ${{ secrets.EC2_KEY_BASE64 }}
        run: |
          echo "$EC2_KEY_BASE64" | base64 --decode > url-shortener-backend.pem
          chmod 400 url-shortener-backend.pem

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }} # Default: "ubuntu"
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no -i url-shortener-backend.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            echo "🔄 Logging into Docker Hub..."
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

            echo "🔄 Pulling the latest backend image..."
            docker pull suryathink/globetrotter:latest

            echo "🛑 Stopping old containers..."
            docker stop globetrotter-container || true
            docker rm globetrotter-container || true

            echo "🧹 Cleaning up old Docker images..."
            docker system prune -af

            echo "🚀 Starting the new container with .env file..."
            docker run --env-file /home/ubuntu/env/.env -d --name globetrotter-container -p 4000:4000 suryathink/globetrotter:latest
          EOF
